apiVersion: 1
datasources:
- name: Managed Prometheus
  type: prometheus
  url: "${workspace_query_url}"
  access: proxy
  isDefault: true
  uid: "${prometheus_datasource}"
  jsonData:
    sigV4Auth: true
    sigV4Region: "${region}"
    sigV4AuthType: default