---
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: my-app-staging
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    project: default
    source:
      repoURL: https://github.com/dbaltor/argocd-test.git
      targetRevision: master
      path: environments/staging/my-app
    destination:
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: false
      syncOptions:
        - Validate=true
        - CreateNamespace=false
        - PrunePropagationPolicy=foreground
        - PruneLast=true
